name: Docker Image CI

on:
  push:
    branches: [ "Sarahsaquin" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker-cicd--tag Sarahsaquin/fireservice
    - uses: actions/checkout@v4
    - name: Push to Dockerhub
      run: docker push Sarahsaquin/fireservice
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.SARAH_DOCKER_USERNAME }} -p ${{ secrets.SARAH_DOCKER_ACCESS_TOKEN }}
