name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag guddytech/fireservice
    - uses: actions/checkout@v4
    - name: Push to Dockerhub
      run: docker push guddytech/fireservice
      
    - name: Login to Docker Hub
      run: docker login -u guddytech -p dckr_pat_MfqSdmL4a0uyv7_UmEZV5nznH3U
