name: Docker Image CI

on:
  push:
    branches: [ "goody" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag goodytech/fireservice
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

      
    - name: Hub Push to Dockerhub
      run:  docker push goodytech/fireservice
