name: Docker Image CI 
 
on:
  push:
    branches: [ "guddy" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag guddytech/fireservice
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.GUDDY_DOCKER_USERNAME }}
        DOCKER_ACCESS_TOKEN: ${{ secrets.GUDDY_DOCKER_ACCESS_TOKEN }}
      run: |
        echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push guddytech/fireservice
      
    
